Hr config server
raquelsouto/microservices pull request #6
Opened 2021-09-07 23:27 UTC by raquelsouto

**Type**: Functionality
**Descriptio**: Configure hr-config-server project and configure hr-worker project as a server client

2021-09-07 23:34 UTC, brunowinkeler requested changes
Precisa de alguns ajustes

2021-09-07 23:34 UTC, brunowinkeler commented on hr-config-server/src/main/java/com/devsuperior/hrconfigserver/HrConfigServerApplication.java
> +	public static void main(String[] args) {
Consertar a indentação para espaços ao invés de tabs

2021-09-07 23:34 UTC, brunowinkeler commented on hr-config-server/src/test/java/com/devsuperior/hrconfigserver/HrConfigServerApplicationTests.java
> +	@Test
Consertar a indentação para espaços ao invés de tabs

2021-09-07 23:34 UTC, brunowinkeler commented on hr-worker/pom.xml
> +			<groupId>org.springframework.cloud</groupId>
Consertar a indentação para espaços ao invés de tabs

2021-09-07 23:34 UTC, brunowinkeler commented on hr-config-server/.gitignore
> +./metadata
Sempre colocar uma linha no final do arquivo

2021-09-07 23:34 UTC, brunowinkeler commented on hr-worker/src/main/resources/bootstrap.properties
> +#management.endpoints.web.exposure.include=*
Sempre colocar uma linha no final de todo arquivo

2021-09-07 23:34 UTC, brunowinkeler commented on hr-config-server/pom.xml
> +	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Consertar a indentação para espaços ao invés de tabs

2021-09-07 23:34 UTC, brunowinkeler commented on hr-config-server/src/main/resources/application.properties
> +
Tem uma linha a mais desnecessária

2021-09-07 23:34 UTC, brunowinkeler commented on hr-worker/src/main/java/com/devsuperior/hrworker/repositories/WorkerRepository.java
> +
Se não tem nada na interface, remover linhas em branco

2021-09-08 17:53 UTC, raquelsouto commented on hr-config-server/src/main/java/com/devsuperior/hrconfigserver/HrConfigServerApplication.java
> +	public static void main(String[] args) {
Corrigido

2021-09-08 17:53 UTC, raquelsouto commented on hr-worker/src/main/resources/bootstrap.properties
> +#management.endpoints.web.exposure.include=*
Corrigido

2021-09-08 17:53 UTC, raquelsouto commented on hr-worker/src/main/java/com/devsuperior/hrworker/repositories/WorkerRepository.java
> +
Corrigido

2021-09-08 17:56 UTC, brunowinkeler approved these changes
Aprovado

2021-09-08 17:57 UTC, raquelsouto commented on hr-config-server/src/test/java/com/devsuperior/hrconfigserver/HrConfigServerApplicationTests.java
> +	@Test
Corrigido

2021-09-08 17:57 UTC, raquelsouto commented on hr-config-server/.gitignore
> +./metadata
Corrigido

2021-09-08 17:57 UTC, raquelsouto commented on hr-config-server/src/main/resources/application.properties
> +
Corrigido

2021-09-08 17:57 UTC, raquelsouto commented on hr-config-server/pom.xml
> +	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Corrigido

2021-09-08 17:57 UTC, merged